version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - shared_pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq


  api-gateway:
    build:
      context: .
      dockerfile: ./services/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./services/api-gateway:/app
      - api-gateway_node_modules:/app/api-gateway/node_modules
    environment:
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASS=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - AUTH_SERVICE_HOST=auth-service
      - AUTH_SERVICE_PORT=3001
    depends_on:
      - postgres
      - rabbitmq
      - auth-service


  auth-service:
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    container_name: auth-service
    ports:
      - "3001:3001"
    volumes:
      - ./services/auth-service:/app/services/auth-service
      - ./Database:/app/Database
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - auth_node_modules:/app/services/auth-service/node_modules
      #- services/auth-service/node_modules:/app/services/auth-service/node_modules
      #- ./services/auth-service/node_modules:/app/services/auth-service/node_modules
      #- auth_node_modules:/app/services/auth-service/node_modules
    environment:
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASS=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - AUTH_SERVICE_HOST=0.0.0.0
      - AUTH_SERVICE_PORT=3001
      - MAILER_SERVICE_HOST=mailer-service
      - MAILER_SERVICE_PORT=3000
    depends_on:
      - postgres
      - rabbitmq
      - mailer-service

  mailer-service:
    build:
      context: .
      dockerfile: ./services/mailer-service/Dockerfile
    container_name: mailer-service
    ports:
      - "3008:3000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASS=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq

  frontend-vue:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend-vue
    volumes:
      - frontend-vue_node_modules:/app/node_modules
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_BASE_URL=/
      - VITE_APP_TITLE=Billing System
    depends_on:
      - api-gateway


  agency-service:
    build: ./services/agency-service
    container_name: agency-service
    ports:
      - "3002:3000"
    volumes:
      - ./services/agency-service:/app/services/agency-service
      - ./Database:/app/Database
    environment:
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASS=postgres
    depends_on:
      - postgres

  contrat-service:
    build:
      context: .
      dockerfile: ./services/contrat-service/Dockerfile
    container_name: contrat-service
    ports:
      - "3003:3000"
    volumes:
      - ./services/contrat-service/src:/app/services/contrat-service/src
      - ./Database:/app/Database
    environment:
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASS=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - AUTH_SERVICE_HOST=0.0.0.0
      - AUTH_SERVICE_PORT=3001
      - MAILER_SERVICE_HOST=mailer-service
      - MAILER_SERVICE_PORT=3000
    depends_on:
      - postgres
      - rabbitmq
      - mailer-service

  intervention-service:
    build:
      context: .
      dockerfile: services/intervention-service/Dockerfile
    container_name: intervention-service
    ports:
      - "3005:3000"
    volumes:
      - ./services/intervention-service:/app/services/intervention-service
      - ./Database:/app/Database
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - intervention-service_node_modules:/app/services/intervention-service/node_modules
    environment:
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASS=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - AUTH_SERVICE_HOST=0.0.0.0
      - AUTH_SERVICE_PORT=3001
      - MAILER_SERVICE_HOST=mailer-service
      - MAILER_SERVICE_PORT=3000
    depends_on:
      - postgres
      - rabbitmq
      - mailer-service

  facture-service:
    build:
      context: .
      dockerfile: services/facture-service/Dockerfile
    container_name: facture-service
    ports:
      - "3006:3000"
    volumes:
      - ./services/facture-service:/app/services/facture-service
      - ./Database:/app/Database
      - ./tsconfig.base.json:/app/tsconfig.base.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./package.json:/app/package.json
      - facture-service_node_modules:/app/services/facture-service/node_modules
    environment:
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASS=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - AUTH_SERVICE_HOST=0.0.0.0
      - AUTH_SERVICE_PORT=3001
      - MAILER_SERVICE_HOST=mailer-service
      - MAILER_SERVICE_PORT=3000
    depends_on:
      - postgres
      - rabbitmq
      - mailer-service

  operation-service:
    build:
      context: .
      dockerfile: ./services/operation-service/Dockerfile
    container_name: operation-service
    ports:
      - "3004:3000"
    volumes:
      - ./services/operation-service/src:/app/services/operation-service/src
      - ./Database:/app/Database
      - operation-service_node_modules:/app/services/operation-service/node_modules
    environment:
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASS=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - AUTH_SERVICE_HOST=0.0.0.0
      - AUTH_SERVICE_PORT=3001
      - MAILER_SERVICE_HOST=mailer-service
      - MAILER_SERVICE_PORT=3000
    depends_on:
      - postgres
      - rabbitmq
      - mailer-service

  workflow-service:
    build:
      context: .
      dockerfile: ./services/workflow-service/Dockerfile
    container_name: workflow-service
    ports:
      - "3007:3000"
    volumes:
      - ./services/workflow-service/src:/app/services/workflow-service/src
      - ./Database:/app/Database
      - workflow-service_node_modules:/app/services/workflow-service/node_modules
    environment:
      - DB_HOST=postgres
      - DB_NAME=main
      - DB_USER=postgres
      - DB_PASS=postgres
      - RABBITMQ_URL=amqp://admin:admin@rabbitmq:5672
      - AUTH_SERVICE_HOST=0.0.0.0
      - AUTH_SERVICE_PORT=3001
      - MAILER_SERVICE_HOST=mailer-service
      - MAILER_SERVICE_PORT=3000
    depends_on:
      - postgres
      - rabbitmq
      - mailer-service

volumes:
  shared_pgdata:
  rabbitmq_data:
  auth_node_modules:
  api-gateway_node_modules:
  agency-service_node_modules:
  contrat-service_node_modules:
  intervention-service_node_modules:
  facture-service_node_modules:
  operation-service_node_modules:
  workflow-service_node_modules:
  frontend-vue_node_modules:
  mailer_node_modules:
