apiVersion: apps/v1
kind: Deployment
metadata:
  name: agency-service
  labels:
    app: agency-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: agency-service
  template:
    metadata:
      labels:
        app: agency-service
    spec:
      containers:
      - name: agency-service
        image: agency-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_NAME
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: agency-service
spec:
  selector:
    app: agency-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
