apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrat-service
  labels:
    app: contrat-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contrat-service
  template:
    metadata:
      labels:
        app: contrat-service
    spec:
      containers:
      - name: contrat-service
        image: contrat-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_HOST
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: contrat-service
spec:
  selector:
    app: contrat-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
