apiVersion: apps/v1
kind: Deployment
metadata:
  name: intervention-service
  labels:
    app: intervention-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intervention-service
  template:
    metadata:
      labels:
        app: intervention-service
    spec:
      containers:
        - name: intervention-service
          image: registry.digitalocean.com/aquaerp-registry/intervention-service:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: intervention-service-secrets
            - configMapRef:
                name: intervention-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: intervention-service
spec:
  selector:
    app: intervention-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 