apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailer-service
  namespace: aquaerp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mailer-service
  template:
    metadata:
      labels:
        app: mailer-service
    spec:
      containers:
      - name: mailer-service
        image: docker.io/yassblh/mailer-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3005
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: app-config
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DATABASE_HOST
              name: app-config
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DATABASE_PORT
              name: app-config
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DATABASE_NAME
              name: app-config
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: postgres-secret
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: password
              name: postgres-secret
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: secret
              name: jwt-secret
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              key: SMTP_HOST
              name: smtp-secret
        - name: SMTP_PORT
          valueFrom:
            secretKeyRef:
              key: SMTP_PORT
              name: smtp-secret
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              key: SMTP_USER
              name: smtp-secret
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              key: SMTP_PASS
              name: smtp-secret
        - name: SMTP_FROM
          valueFrom:
            secretKeyRef:
              key: SMTP_FROM
              name: smtp-secret
        - name: RABBITMQ_URL
          value: "amqp://admin:admin@rabbitmq:5672"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3005
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mailer-service
  namespace: aquaerp
spec:
  type: ClusterIP
  ports:
  - port: 3005
    targetPort: 3005
  selector:
    app: mailer-service 