apiVersion: v1
kind: Secret
metadata:
  name: mailer-smtp-secret
  namespace: aquaerp
stringData:
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
  SMTP_SECURE: "false"
  SMTP_USER: "user@domaine.com"
  SMTP_PASS: "votre_mot_de_passe"
  SMTP_FROM: "Water App <noreply@aquaerp.cloud>" 