apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: billing-app
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin
  RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672