apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: aquaerp
type: Opaque
data:
  username: YXF1YWVycA==  # aquaerp
  password: YXF1YWVycHBhc3N3b3Jk  # aquaerppassword
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: aquaerp
type: Opaque
data:
  secret: YXF1YWVycC1qd3Qtc2VjcmV0LWtleQ==  # aquaerp-jwt-secret-key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: aquaerp
data:
  NODE_ENV: "production"
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "aquaerp"
  JWT_SECRET: "aquaerp-jwt-secret-key" 