apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  labels:
    app: auth-service
type: Opaque
data:
  DATABASE_URL: <base64-encoded-url>
  JWT_SECRET: <base64-encoded-secret>
  SENTRY_DSN: <base64-encoded-dsn> 