FROM node:20-alpine AS builder

WORKDIR /app

COPY ./package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Étape finale, plus légère
FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist ./dist
RUN npm install --only=production

EXPOSE 3003

CMD ["npm", "run", "start:prod"]
