name: CI/CD Deploy AquaERP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: registry.digitalocean.com/factu-reg
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DigitalOcean Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push images
        run: |
          docker build --platform linux/amd64 -t $REGISTRY/auth-service:$IMAGE_TAG -f services/auth-service/Dockerfile .
          docker push $REGISTRY/auth-service:$IMAGE_TAG
          docker tag $REGISTRY/auth-service:$IMAGE_TAG $REGISTRY/auth-service:latest
          docker push $REGISTRY/auth-service:latest
          docker build --platform linux/amd64 -t $REGISTRY/api-gateway:$IMAGE_TAG -f services/api-gateway/Dockerfile .
          docker push $REGISTRY/api-gateway:$IMAGE_TAG
          docker tag $REGISTRY/api-gateway:$IMAGE_TAG $REGISTRY/api-gateway:latest
          docker push $REGISTRY/api-gateway:latest
          docker build --platform linux/amd64 -t $REGISTRY/contrat-service:$IMAGE_TAG -f services/contrat-service/Dockerfile .
          docker push $REGISTRY/contrat-service:$IMAGE_TAG
          docker tag $REGISTRY/contrat-service:$IMAGE_TAG $REGISTRY/contrat-service:latest
          docker push $REGISTRY/contrat-service:latest
          docker build --platform linux/amd64 -t $REGISTRY/facture-service:$IMAGE_TAG -f services/facture-service/Dockerfile .
          docker push $REGISTRY/facture-service:$IMAGE_TAG
          docker tag $REGISTRY/facture-service:$IMAGE_TAG $REGISTRY/facture-service:latest
          docker push $REGISTRY/facture-service:latest
          docker build --platform linux/amd64 -t $REGISTRY/intervention-service:$IMAGE_TAG -f services/intervention-service/Dockerfile .
          docker push $REGISTRY/intervention-service:$IMAGE_TAG
          docker tag $REGISTRY/intervention-service:$IMAGE_TAG $REGISTRY/intervention-service:latest
          docker push $REGISTRY/intervention-service:latest
          docker build --platform linux/amd64 -t $REGISTRY/mailer-service:$IMAGE_TAG -f services/mailer-service/Dockerfile .
          docker push $REGISTRY/mailer-service:$IMAGE_TAG
          docker tag $REGISTRY/mailer-service:$IMAGE_TAG $REGISTRY/mailer-service:latest
          docker push $REGISTRY/mailer-service:latest
          docker build --platform linux/amd64 -t $REGISTRY/operation-service:$IMAGE_TAG -f services/operation-service/Dockerfile .
          docker push $REGISTRY/operation-service:$IMAGE_TAG
          docker tag $REGISTRY/operation-service:$IMAGE_TAG $REGISTRY/operation-service:latest
          docker push $REGISTRY/operation-service:latest
          docker build --platform linux/amd64 -t $REGISTRY/workflow-service:$IMAGE_TAG -f services/workflow-service/Dockerfile .
          docker push $REGISTRY/workflow-service:$IMAGE_TAG
          docker tag $REGISTRY/workflow-service:$IMAGE_TAG $REGISTRY/workflow-service:latest
          docker push $REGISTRY/workflow-service:latest
          docker build --platform linux/amd64 -t $REGISTRY/frontend:$IMAGE_TAG -f frontend/Dockerfile .
          docker push $REGISTRY/frontend:$IMAGE_TAG
          docker tag $REGISTRY/frontend:$IMAGE_TAG $REGISTRY/frontend:latest
          docker push $REGISTRY/frontend:latest

      - name: Set up Kubeconfig
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save kubeconfig
        run: doctl kubernetes cluster kubeconfig save factu

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/ 